language: node_js
node_js:
- '10.16'
services:
  - xvfb
before_install:
- export CHROME_BIN=/usr/bin/google-chrome
- export DISPLAY=:99.0
script:
- npm run build
- npm test
- VER_DEPL=$(npm show opentok-accelerator-core version);
- VERSION=$(jq '.version' package.json | sed -e 's/^"//' -e 's/"$//');
- if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "main" && "$VER_DEPL" != "$VERSION" ]]; then
    git commit -m "New build. Bump npm version." --allow-empty;
    git tag v$VERSION;
    git push --quiet https://$GITHUBKEY@github.com/opentok/accelerator-core-js v$VERSION;
  fi
deploy:
  provider: npm
  email: vsolutions@tokbox.com
  api_key: $NPM_TOKEN
  on:
    branch: main
    condition: $VERSION != $VER_DEPL
  skip_cleanup: true
notifications:
  slack:
    secure: csFMBAr1OOgB41jMXzwVzrO58PsOdFSRnyN+h0nXfEd0aL1UbrOxbgqqMwpWJwkZnJENnVuW1tkxFXoGnq6sJjOywLPkPqCf0dPGEWTUvbsdsFrNivtNbjT/kY3BI5sz13ENGyZuzD68bQ/Za7JQUgAlkOX0jlml8ZtBABkvPQaFAcqDHoiZrTgSjv5rvwHC6Wo8Fi50PsE662X7HtIrLCk+Xaoi5rzTf/5vB3gGJysCV3qmB6t+9QOBElmjPERHOfVLkKiexjDJQ3jSBmR164vUZL0207+Y9GuyDq0iTHumEu5LK+xoAikOFRoGVH0iWUCtrJPg/SeWCJ1KxKI1Fymc2atQ7zTXyZxj18GrB3xxkW3qH/1rNH8OJoV6bHTr8tNaoRHGbwawo0hioEQ7h5X4b0xHAqpyJq1QcbZ7rBJu7sKIxP58qBztzL+Bzue35BNE1N1AVcN3YPU0jxDFSHKAG0ZVgI9hjU0IvLg5YoIaNZCN4MC6C1LVDknxGfjjC6oNE1oOz9xtIw1FNf5SbvoKrmCuqG2qDEQ87QwWTpzXaZajExF6C4p+gMtK3MJjWuCV5AILjc+XLJ7y9AVr5i9ErwTdyXAV5ACUw3riDUklKHGetGA3SPeSO9Lg35yb4OgPoNcZSSZ7y4WZg6iVPaI/gZbLk6PqKFlQZO5jCHg=
